# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: sampleagentpool  # Use your self-hosted agent pool name
  demands:
    - agent.name -equals sampleagent  # Optional: Ensures a specific agent runs it

variables:
  buildConfiguration: 'Release'
  azureWebAppName: 'angapp'  # Replace with your actual web app name
  azureSubscription: 'myazuresubscription'  # Replace with your Azure subscription name

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    pool:
      name: sampleagentpool  # Use your self-hosted agent pool name
    steps:
    - script: dotnet build --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
      displayName: 'dotnet build $(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build  # Ensures the deploy stage runs after the build stage
  jobs:
  - job: DeployJob
    pool:
      name: sampleagentpool  # Use your self-hosted agent pool name
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(azureWebAppName)
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        deploymentMethod: 'auto'
