trigger:
    - master # Adjust the branch name as needed

pool:
    vmImage: windows-latest # Windows machine for .NET apps

variables:
    buildConfiguration: "Release"

steps:
    - task: UseDotNet@2
      inputs:
          packageType: "sdk"
          version: "8.x" # Adjust to your .NET version
          installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
          dotnet restore api.csproj
          dotnet build api.csproj --configuration $(buildConfiguration)
      displayName: "Restore & Build"

    # Create EF Core Migration bundle
    - script: |
          dotnet tool install --global dotnet-ef
          dotnet ef migrations bundle --project api.csproj --output efbundle
      displayName: "Create EF Migration Bundle"

    # Run EF migrations
    - powershell: |
          .\efbundle --connection "$env:DB_CONNECTION_STRING"
      displayName: "Create and Run EF Core Migration"
      env:
          DB_CONNECTION_STRING: $(DB_CONNECTION_STRING)

    - script: |
          dotnet publish api.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
      displayName: "Publish"

    # Zip the published artifacts (optional, depending on your needs)
    - task: ArchiveFiles@2
      inputs:
          rootFolderOrFile: "$(Build.ArtifactStagingDirectory)" # Path to the publish folder
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/api.zip"
          replaceExistingArchive: true
      displayName: "Zip Published Artifacts"

    # Publish the zipped artifact (for storage in Azure DevOps artifacts, for later use)
    - task: PublishBuildArtifacts@1
      inputs:
          pathToPublish: "$(Build.ArtifactStagingDirectory)/api.zip"
          artifactName: "drop"
          publishLocation: "Container"
      displayName: "Publish Zipped Artifacts"
