trigger:
- master  # Change to 'main' if needed

pool:
  vmImage: windows-latest  # Use 'windows-latest' if needed

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Change if using .NET 7 or 6
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore api.csproj
    dotnet build api.csproj --configuration $(buildConfiguration)
  displayName: 'Restore & Build'

- script: |
    dotnet publish api.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
